### ISSUE TITLE
镜像下载速度变得很慢

### ISSUE THREAD

**Issue by Patrick-Ni** [git-cloner/aliendao#1]
今天下载模型的时候发现下载速度变得非常慢，几秒1MB，请问大佬能看一下吗
![image](https://github.com/git-cloner/aliendao/assets/59468866/1655deb9-7be9-4372-a74d-4c6d69f9fd03)

**Comment by Patrick-Ni** [comment]
补充：wget也只有几百kb/s
![image](https://github.com/git-cloner/aliendao/assets/59468866/c93f3994-26bc-4abe-b468-84eff7ad484c)

**Comment by little51** [comment]
由于hf好几天无法连接，导致aliendao.cn访问量剧增，200m入口带宽全跑满了，如果明天还是这样情况，我想办法限一下单个请求速度和禁止迅雷等下载请求

**Comment by Patrick-Ni** [comment]
非常感谢您的回复！！

**Comment by little51** [comment]
感谢您对aliendao.cn的支持，已加了单连接限速，如遇到下载速度问题，可发邮件到gitclone@126.com

**Comment by 786121272** [comment]
作者您好，能否考虑提供更多下载方式，比如上传网盘，让用户自行转存后下载等等，现在的下载速度实在是太慢了

**Comment by little51** [comment]
你好，网盘没那么多的空间，现在问题主要是带宽，己在扩容过程中

**Comment by little51** [comment]
已扩容，速度有所提升

**Comment by CarhoJohn** [comment]
我用服务器下载模型，还是很慢诶，几百kb。是带宽又被占满了吗？

![image](https://github.com/git-cloner/aliendao/assets/45853320/4862a952-e822-4410-bac0-7ed9bc40af05)

**Comment by zaoqishibing** [comment]
大佬，速度更慢了，你这是一个公益项目吗
![image](https://github.com/git-cloner/aliendao/assets/17840273/8ce95daa-68aa-4be7-8443-d300b64fd7fe)

**Comment by little51** [comment]
免费项目，再扩带宽费用太高了

**Comment by ravens510127** [comment]
我本来想转到gitee再下载的，发现已经有人转过了，然而gitee的lfs功能居然要收费

**Comment by little51** [comment]
lfs太耗带宽了，模型都很大，一般13G起步
