### ISSUE TITLE
公司有代理的情况下，如何下载呢？

### ISSUE THREAD

**Issue by micrazy** [git-cloner/aliendao#10]
python model_download.py --repo_id stabilityai/stable-diffusion-xl-base-1.0 --mirror

报错
requests.exceptions.SSLError: HTTPSConnectionPool(host='e.aliendao.cn', port=443): Max retries exceeded with url: /models/stabilityai/stable-diffusion-xl-base-1.0?json=true (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))

尝试model_download.pyli 151行增加proxy不行
尝试把model_download.pyli 150行替换https为http也不行

**Comment by little51** [comment]
e.aliendao.cn在阿里云，不需要proxy

**Comment by micrazy** [comment]
> e.aliendao.cn在阿里云，不需要proxy

我是指公司内网访问公司外网的proxy

**Comment by little51** [comment]
e.aliendao.cn在阿里云，访问e.aliendao.cn不需要proxy就可以用。但你公司用proxy，因为我不了解proxy是如何设置的，所以也不好说是具体解决。

**Comment by micrazy** [comment]
好吧，我再试试，如果解决给你提pr

**Comment by little51** [comment]
好的，多谢
