### ISSUE TITLE
运行命令时报错

### ISSUE THREAD

**Issue by Carry-yogurt** [git-cloner/aliendao#13]
使用命令 python model_download.py --repo_id Qwen/Qwen-VL-Chat --mirror 时，报错TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by little51** [comment]
model_download.py 是否使用了最新的？

**Comment by Carry-yogurt** [comment]
> model_download.py 是否使用了最新的？
是的，是直接从您项目中克隆下来的，可以拉取Qwen7B的那个模型，是我这条命令有问题吗？

**Comment by little51** [comment]
命令格式没有问题，是没这个镜像

**Comment by Carry-yogurt** [comment]
好的好的，十分感谢
