### ISSUE TITLE
下载模型报错

### ISSUE THREAD

**Issue by liiuzq-xiaobai** [git-cloner/aliendao#3]
![image](https://github.com/git-cloner/aliendao/assets/70749713/25a6fac3-9a0c-460f-814c-fdc2d49850f7)

**Comment by little51** [comment]
命令为：python model_download.py --mirror --repo_id baichuan-inc/Baichuan2-7B-Base ，请核对一下。从报错上看，是与61.33.217.142 不通，ping一下或curl http://61.133.217.142:20800/ ，确认一下通一通
