### ISSUE TITLE
希望增加功能，可以选择单独下载模型中的单个文件

### ISSUE THREAD

**Issue by donglsci** [git-cloner/aliendao#5]
因为下载速度原因，想节省点时间，所以希望能增加单独下载文件的功能，当只需要模型中的单个文件时候，可以单独下载，谢谢

**Comment by little51** [comment]
直接从网站上下载单个文件就可以了

**Comment by donglsci** [comment]
主要是针对镜像站没有的文件，昨天安装Fooocus碰到提示，Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to D:\GitHub\Fooocus-MRE-v2.0.19\Fooocus-MRE\models\prompt_expansion\fooocus_expansion\pytorch_model.bin，这个文件在镜像站找过了没有，但这个下载器还能工作，虽然速度慢点，所以想到了如果能单独下载某个文件，这样就更灵活了。

**Comment by donglsci** [comment]
今天碰巧看到了，[huggingface_tool](https://github.com/OpenRL-Lab/huggingface_tool)，试了一下，能下载单个文件。不过没找到token的填入位置，也可能是自动获取的。

**Comment by little51** [comment]
@donglsci 这个huggingface_tool必须保证hf是能访问的
