### ISSUE TITLE
现在镜像是停了吗？目前都下载不了！

### ISSUE THREAD

**Issue by cxj01** [git-cloner/aliendao#6]

**Comment by little51** [comment]
![1695354837912](https://github.com/git-cloner/aliendao/assets/7981353/f75669d9-7b33-4bc1-a2c2-e487fb2806b5)
正常的啊

**Comment by little51** [comment]
如果是aliendao.cn没有的镜像，的确是用下载器下载不了，因为hf断了，对于aliendao.cn没有的镜像，下载器是转发到hf的

**Comment by cxj01** [comment]
@little51 我的就不行，连不上
![image](https://github.com/git-cloner/aliendao/assets/37614132/c0a76155-db3b-4934-bc14-8306fe3b9a38)

**Comment by little51** [comment]
你看一下是不是到http://61.133.217.142:20800/不通，镜像没停，而且您下载的这个模型aliendao里是有的

**Comment by cxj01** [comment]
@little51 我可以ping 通 61.133.217.142，但是还是报上述错误。
![image](https://github.com/git-cloner/aliendao/assets/37614132/40fe8686-6e1d-4c3d-b98f-a3a659b4c2ed)
![image](https://github.com/git-cloner/aliendao/assets/37614132/06c94e29-6d20-4ebd-b81e-b8844ef3bbed)

**Comment by little51** [comment]
http://61.133.217.142:20800/download/models/baichuan-inc/Baichuan-7B/README.md
试一下这个

**Comment by cxj01** [comment]
@little51 虽然可以ping通ip，但是使用wget下载不了
![image](https://github.com/git-cloner/aliendao/assets/37614132/f4fdf15f-87b1-4e5e-964a-e654a3d4e209)

> http://61.133.217.142:20800/download/models/baichuan-inc/Baichuan-7B/README.md 试一下这个

**Comment by little51** [comment]
一种情况是你用了代理，二种情况是你的网络的路由问题，三种情况被我这的防火墙给拒了（你用你的手机浏览器，用流量，不用要wifi，打开一下上述地址验证一下），你用traceroute 61.133.217.142，把结果发到我的邮箱，我看一下你的IP

**Comment by hanbon** [comment]
出现了同样的问题，请问下后面有解决吗~解决了踢踢我

**Comment by hanbon** [comment]
![image](https://github.com/git-cloner/aliendao/assets/10284997/ecf7e439-bf79-404f-954a-ffd0a3f1b8f9)

**Comment by hanbon** [comment]
![image](https://github.com/git-cloner/aliendao/assets/10284997/9808725c-1281-47e8-a04c-845120c1e31b)
traceroute的结果

**Comment by hanbon** [comment]
@little51

**Comment by little51** [comment]
我这防火墙上拒绝连接的有以下IP：120.48.85.15，211.137.7.246，111.17.194.85，42.81.211.119，140.249.62.25，60.27.241.68。看一下traceroute中有没有出现过这些IP，如有误伤的情况，请发邮件到gitclone@126.com，感谢大家的支持。

**Comment by little51** [comment]
我这防火墙上拒绝连接的有以下IP：120.48.85.15，211.137.7.246，111.17.194.85，42.81.211.119，140.249.62.25，60.27.241.68。看一下traceroute中有没有出现过这些IP，如有误伤的情况，请发邮件到gitclone@126.com，感谢大家的支持。@hanbon 我看你怎用的80端口？正确应用61.133.217.142:20800

**Comment by hua-zi** [comment]
> 我这防火墙上拒绝连接的有以下IP：120.48.85.15，211.137.7.246，111.17.194.85，42.81.211.119，140.249.62.25，60.27.241.68。看一下traceroute中有没有出现过这些IP，如有误伤的情况，请发邮件到[gitclone@126.com](mailto:gitclone@126.com)，感谢大家的支持。@hanbon 我看你怎用的80端口？正确应用61.133.217.142:20800

![image](https://github.com/git-cloner/aliendao/assets/83271073/07336c9b-c610-4d10-88ac-238c323da7dc)
我并没有设置80端口，为什么报错这里显示80端口呀

**Comment by little51** [comment]
这个80端口不也不了解是什么原因，我怀疑是我在防火墙上refuse的那几个IP有你的源地址。你从网站上复制链接地址试，或者用手机流量试

**Comment by little51** [comment]
这个80端口不也不了解是什么原因，我怀疑是我在防火墙上refuse的那几个IP有你的源地址。你从网站上复制链接地址试，或者用手机流量试
