### ISSUE TITLE
下载的镜像文件为0kb

### ISSUE THREAD

**Issue by leap233** [git-cloner/aliendao#7]
请问为什么我下载的镜像文件都是0KB(所有文件都是0KB)

python model_download.py --mirror --repo_id baichuan-inc/Baichuan2-13B-Chat

这是我下载的模型

**Comment by little51** [comment]
在下载完成之前，./dataroot/models下正在下载的文件是0字节，但已下载完成的文件，大小的正常的，检查一下是不是硬盘满了
